"""
NASA JSC Flickr Photos Metadata Retriever

This script reads the photosets list generated by 9e_get_jsc_flickr_list.py and
fetches detailed metadata for every photo in each album/photoset.

For each album, it creates a separate JSON file containing:
- Album metadata (title, description, etc.)
- Complete list of photos with detailed metadata (excluding duplicates)
- Photo URLs in various sizes
- EXIF data (optional)
- Tags, descriptions, geo location data
- Upload and taken dates

The script includes:
- Rate limiting to respect Flickr's API limits
- Photo caching to avoid duplicate API calls for photos that appear in multiple albums
- Deduplication to avoid storing the same photo in multiple album outputs
- Support for resuming interrupted downloads by skipping already processed albums
- Periodic cache saving every 10 photos processed for better progress preservation

Output:
- One JSON file per album in RAW_FOLDER/photos_flickr/albums/ (no duplicate photos)
- Photo cache file: RAW_FOLDER/photos_flickr/photo_cache.json (tracks processed photo IDs)
"""

import json
import os
import requests
from pathlib import Path
from dotenv import load_dotenv
import sys
from datetime import datetime
import time

# Load environment variables
load_dotenv(dotenv_path="../../../.env")

FLICKR_API_KEY = os.getenv("FLICKR_API_KEY")
FLICKR_API_SECRET = os.getenv("FLICKR_API_SECRET")
RAW_FOLDER = os.getenv("RAW_FOLDER")

if not RAW_FOLDER:
    print("Error: RAW_FOLDER environment variable not found")
    sys.exit(1)

INPUT_FOLDER = RAW_FOLDER + "photos_flickr/"
OUTPUT_FOLDER = RAW_FOLDER + "photos_flickr/albums/"

# Flickr API constants
FLICKR_API_BASE_URL = "https://www.flickr.com/services/rest/"
TARGET_USERNAME = "nasa2explore"

# Rate limiting
REQUEST_DELAY = 0.5  # Delay between API requests in seconds

# Photo cache for avoiding duplicate API calls and deduplication
PHOTO_CACHE_FILE = os.path.join(INPUT_FOLDER, "photo_cache.json")
photo_cache = set()  # Set of photo IDs that have been processed
cache_hits = 0
cache_misses = 0


def make_flickr_api_request(method, params=None, max_retries=3):
    """
    Make a request to the Flickr API with rate limiting and retry logic

    Args:
        method: Flickr API method name
        params: Additional parameters for the API call
        max_retries: Maximum number of retries for rate limit errors

    Returns:
        JSON response from the Flickr API
    """
    if params is None:
        params = {}

    # Add required parameters
    params.update(
        {
            "api_key": FLICKR_API_KEY,
            "method": method,
            "format": "json",
            "nojsoncallback": "1",
        }
    )

    for attempt in range(max_retries + 1):
        try:
            # Rate limiting
            time.sleep(REQUEST_DELAY)

            response = requests.get(FLICKR_API_BASE_URL, params=params)
            response.raise_for_status()
            data = response.json()

            # Check for Flickr API error
            if data.get("stat") == "fail":
                error_code = data.get("code")
                error_message = data.get("message", "Unknown error")

                # Handle rate limiting (429) with exponential backoff
                if (
                    error_code == 105
                ):  # Service currently unavailable (often rate limit)
                    if attempt < max_retries:
                        backoff_delay = REQUEST_DELAY * (
                            2**attempt
                        )  # Exponential backoff
                        print(
                            f"Rate limit hit (attempt {attempt + 1}/{max_retries + 1}), waiting {backoff_delay:.1f}s before retry..."
                        )
                        time.sleep(backoff_delay)
                        continue
                    else:
                        print(
                            f"Rate limit error after {max_retries + 1} attempts: {error_message}"
                        )
                        return None
                else:
                    print(f"Flickr API error: {error_message}")
                    print(f"Error code: {error_code}")
                    return None

            return data

        except requests.RequestException as e:
            if hasattr(e.response, "status_code") and e.response.status_code == 429:
                if attempt < max_retries:
                    backoff_delay = REQUEST_DELAY * (2**attempt)
                    print(
                        f"HTTP 429 Too Many Requests (attempt {attempt + 1}/{max_retries + 1}), waiting {backoff_delay:.1f}s before retry..."
                    )
                    time.sleep(backoff_delay)
                    continue
                else:
                    print(f"HTTP 429 error after {max_retries + 1} attempts: {e}")
                    return None
            else:
                print(f"Error making Flickr API request: {e}")
                return None
        except json.JSONDecodeError:
            print("Error: Failed to parse JSON response from Flickr API.")
            return None

    return None


def get_photoset_photos(photoset_id, page=1, per_page=500):
    """
    Get all photos in a photoset

    Args:
        photoset_id: The photoset ID
        page: Page number (default: 1)
        per_page: Number of photos per page (default: 500, max allowed)

    Returns:
        Photos data or None if error
    """
    print(f"  Fetching photos for photoset {photoset_id}, page {page}")

    params = {
        "photoset_id": photoset_id,
        "page": page,
        "per_page": per_page,
        "extras": "description,license,date_upload,date_taken,owner_name,icon_server,original_format,last_update,geo,tags,machine_tags,o_dims,views,media,path_alias,url_sq,url_t,url_s,url_m,url_o,url_l,url_c,url_z,url_n,url_w,url_h,url_k,url_3k,url_4k,url_f,url_5k,url_6k",
    }

    data = make_flickr_api_request("flickr.photosets.getPhotos", params)

    if data and "photoset" in data:
        photoset_info = data["photoset"]
        photos = photoset_info.get("photo", [])

        print(f"    Found {len(photos)} photos on page {page}")

        return {
            "photos": photos,
            "page": photoset_info.get("page", 1),
            "pages": photoset_info.get("pages", 1),
            "per_page": photoset_info.get("perpage", per_page),
            "total": photoset_info.get("total", 0),
            "photoset_id": photoset_info.get("id", photoset_id),
            "title": photoset_info.get("title", ""),
        }
    else:
        print(f"    No photos found or error occurred for photoset {photoset_id}")
        return None


def load_photo_cache():
    """
    Load photo cache from file if it exists

    Returns:
        True if cache loaded successfully, False otherwise
    """
    global photo_cache

    if os.path.exists(PHOTO_CACHE_FILE):
        try:
            with open(PHOTO_CACHE_FILE, "r", encoding="utf-8") as f:
                cache_data = json.load(f)
                photo_cache = set(cache_data.get("cached_photo_ids", []))
                print(f"✓ Loaded photo cache with {len(photo_cache)} photos")
                return True
        except Exception as e:
            print(f"Warning: Could not load photo cache: {e}")
            photo_cache = set()
            return False
    else:
        print("No existing photo cache found, starting fresh")
        photo_cache = set()
        return True


def save_photo_cache():
    """
    Save photo cache to file

    Returns:
        True if saved successfully, False otherwise
    """
    global photo_cache

    try:
        # Create cache directory if it doesn't exist
        os.makedirs(os.path.dirname(PHOTO_CACHE_FILE), exist_ok=True)

        cache_data = {
            "metadata": {
                "created_at": datetime.now().isoformat(),
                "total_cached": len(photo_cache),
                "cache_file": PHOTO_CACHE_FILE,
            },
            "cached_photo_ids": list(photo_cache),
        }

        with open(PHOTO_CACHE_FILE, "w", encoding="utf-8") as f:
            json.dump(cache_data, f, indent=2, ensure_ascii=False)

        print(
            f"✓ Saved photo cache with {len(photo_cache)} photos to {PHOTO_CACHE_FILE}"
        )
        return True

    except Exception as e:
        print(f"Error saving photo cache: {e}")
        return False


def get_photo_info(photo_id):
    """
    Get detailed information for a specific photo

    Args:
        photo_id: The photo ID

    Returns:
        Photo info data or None if error
    """
    params = {
        "photo_id": photo_id,
        "secret": "",  # Not required for public photos
    }

    data = make_flickr_api_request("flickr.photos.getInfo", params)

    if data and "photo" in data:
        return data["photo"]
    else:
        print(f"    Could not get detailed info for photo {photo_id}")
        return None


def get_photo_exif(photo_id):
    """
    Get EXIF data for a specific photo

    Args:
        photo_id: The photo ID

    Returns:
        EXIF data or None if error/not available
    """
    params = {
        "photo_id": photo_id,
    }

    data = make_flickr_api_request("flickr.photos.getExif", params)

    if data and "photo" in data:
        return data["photo"].get("exif", [])
    else:
        # EXIF might not be available for all photos
        return None


def get_cached_photo_info(photo_id, include_detailed_info=True, include_exif=False):
    """
    Get photo info - cache just tracks which IDs have been fetched to avoid duplicates

    Args:
        photo_id: The photo ID
        include_detailed_info: Whether to include detailed info
        include_exif: Whether to include EXIF data

    Returns:
        Photo metadata dict or None if error
    """
    global photo_cache, cache_hits, cache_misses

    # Check if photo is already in cache (shouldn't happen with deduplication, but safety check)
    if photo_id in photo_cache:
        cache_hits += 1
        print(f"    Unexpected cache hit for photo {photo_id} - skipping")
        return None

    # Photo not in cache, fetch it
    cache_misses += 1
    print(f"    Fetching photo {photo_id} from API")

    photo_data = {"id": photo_id}

    # Get detailed photo info if requested
    if include_detailed_info:
        detailed_info = get_photo_info(photo_id)
        if detailed_info:
            photo_data["detailed_info"] = detailed_info

    # Get EXIF data if requested
    if include_exif:
        exif_data = get_photo_exif(photo_id)
        if exif_data:
            photo_data["exif"] = exif_data

    # Add to cache (just the ID) - this happens after processing in the calling function
    # photo_cache.add(photo_id)  # Moved to calling function

    return photo_data


def process_photoset(
    photoset_data, include_detailed_info=True, include_exif=False, existing_data=None
):
    """
    Process a single photoset and get all its photos with metadata

    Args:
        photoset_data: Photoset information from the albums list
        include_detailed_info: Whether to fetch detailed photo info
        include_exif: Whether to fetch EXIF data (may not be available)
        existing_data: Existing photoset data to resume from

    Returns:
        Complete photoset data with all photos
    """
    global processed_photos

    photoset_id = photoset_data.get("id")
    photoset_title = photoset_data.get("title", {}).get("_content", "Untitled")

    print(f"Processing photoset: {photoset_title} (ID: {photoset_id})")

    # Get first page to determine total pages
    photos_data = get_photoset_photos(photoset_id)
    if not photos_data:
        return None

    all_photos = photos_data["photos"]
    total_pages = photos_data["pages"]

    # Get remaining pages if any
    if total_pages > 1:
        print(f"  Photoset has {total_pages} pages, fetching remaining pages...")
        for page in range(2, total_pages + 1):
            page_data = get_photoset_photos(photoset_id, page=page)
            if page_data and "photos" in page_data:
                all_photos.extend(page_data["photos"])

    print(f"  Total photos in photoset: {len(all_photos)}")

    # Load existing photos if resuming
    existing_photos = []
    if existing_data and "photos" in existing_data:
        existing_photos = existing_data["photos"]
        existing_photo_ids = {photo.get("id") for photo in existing_photos}
        print(f"  Found {len(existing_photos)} existing photos in output file")

        # Filter out photos that are already in the existing data
        all_photos = [
            photo for photo in all_photos if photo.get("id") not in existing_photo_ids
        ]
        print(f"  {len(all_photos)} new photos to process")

    # Filter out photos that have already been processed (using photo_cache for deduplication)
    original_count = len(all_photos)
    all_photos = [photo for photo in all_photos if photo.get("id") not in photo_cache]
    skipped_count = original_count - len(all_photos)

    if skipped_count > 0:
        print(f"  Skipped {skipped_count} photos already processed in other albums")

    print(f"  Photos to process: {len(all_photos)}")

    # Calculate total count for metadata
    total_original_count = len(existing_photos) + original_count + skipped_count

    # Enhance photos with detailed information if requested
    if include_detailed_info and all_photos:
        print(f"  Fetching detailed information for {len(all_photos)} photos...")
        for i, photo in enumerate(all_photos, 1):
            photo_id = photo.get("id")
            if photo_id:
                print(f"    Processing photo {i}/{len(all_photos)}: {photo_id}")

                # Get cached or fetch photo metadata
                photo_metadata = get_cached_photo_info(
                    photo_id, include_detailed_info, include_exif
                )
                if photo_metadata:
                    # Merge the metadata into the photo object
                    if "detailed_info" in photo_metadata:
                        photo["detailed_info"] = photo_metadata["detailed_info"]
                    if "exif" in photo_metadata:
                        photo["exif"] = photo_metadata["exif"]

                # Mark this photo as processed
                photo_cache.add(photo_id)

            # Save partial results every 50 photos to enable resuming
            if i % 50 == 0 or i == len(all_photos):
                print(f"    Saving partial results after {i} photos...")
                partial_photos = existing_photos + all_photos[:i]
                partial_output_data = {
                    "metadata": {
                        "photoset_id": photoset_id,
                        "photoset_title": photoset_title,
                        "username": TARGET_USERNAME,
                        "retrieved_at": datetime.now().isoformat(),
                        "flickr_api_version": "1.0",
                        "total_photos_in_album": total_original_count,
                        "photos_processed": i,
                        "photos_skipped": skipped_count,
                        "photos_from_existing": len(existing_photos),
                        "include_detailed_info": include_detailed_info,
                        "include_exif": include_exif,
                        "partial_save": True,
                        "last_saved_at": datetime.now().isoformat(),
                    },
                    "photoset_info": photoset_data,
                    "photos": partial_photos,
                }
                save_photoset_data(partial_output_data, photoset_id, photoset_title)

    # Combine existing and new photos
    final_photos = existing_photos + all_photos

    # Prepare output data
    output_data = {
        "metadata": {
            "photoset_id": photoset_id,
            "photoset_title": photoset_title,
            "username": TARGET_USERNAME,
            "retrieved_at": datetime.now().isoformat(),
            "flickr_api_version": "1.0",
            "total_photos_in_album": total_original_count,
            "photos_processed": len(all_photos),
            "photos_skipped": skipped_count,
            "photos_from_existing": len(existing_photos),
            "include_detailed_info": include_detailed_info,
            "include_exif": include_exif,
        },
        "photoset_info": photoset_data,
        "photos": final_photos,
    }

    return output_data


def save_photoset_data(photoset_data, photoset_id, photoset_title):
    """
    Save photoset data to a JSON file

    Args:
        photoset_data: The photoset data to save
        photoset_id: The photoset ID for filename
        photoset_title: The photoset title for filename

    Returns:
        True if successful, False otherwise
    """
    # Create safe filename from title and ID
    safe_title = "".join(
        c for c in photoset_title if c.isalnum() or c in (" ", "-", "_")
    ).rstrip()
    safe_title = safe_title.replace(" ", "_")[:50]  # Limit length

    filename = f"{safe_title}_{photoset_id}.json"
    output_file = os.path.join(OUTPUT_FOLDER, filename)

    # Create output directory if it doesn't exist
    os.makedirs(OUTPUT_FOLDER, exist_ok=True)

    try:
        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(photoset_data, f, indent=2, ensure_ascii=False)

        print(f"  Saved photoset data to: {output_file}")
        return True

    except Exception as e:
        print(f"  Error saving photoset data to file: {e}")
        return False


def load_existing_photoset_data(photoset_id, photoset_title):
    """
    Load existing photoset data if it exists

    Args:
        photoset_id: The photoset ID
        photoset_title: The photoset title

    Returns:
        Existing photoset data dict or None if not found
    """
    # Create safe filename from title and ID
    safe_title = "".join(
        c for c in photoset_title if c.isalnum() or c in (" ", "-", "_")
    ).rstrip()
    safe_title = safe_title.replace(" ", "_")[:50]  # Limit length

    filename = f"{safe_title}_{photoset_id}.json"
    file_path = os.path.join(OUTPUT_FOLDER, filename)

    if os.path.exists(file_path):
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            print(f"  Found existing output file: {filename}")
            return data
        except Exception as e:
            print(f"  Warning: Could not load existing file {filename}: {e}")
            return None
    return None


def load_photosets_list():
    """
    Load the photosets list created by 9e_get_jsc_flickr_list.py

    Returns:
        Photosets data or None if error
    """
    input_file = os.path.join(INPUT_FOLDER, f"{TARGET_USERNAME}_photosets.json")

    if not os.path.exists(input_file):
        print(f"Error: Photosets file not found: {input_file}")
        print(
            "Please run 9e_get_jsc_flickr_list.py first to generate the photosets list."
        )
        return None

    try:
        with open(input_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        print(f"Loaded photosets list from: {input_file}")
        return data

    except Exception as e:
        print(f"Error loading photosets list: {e}")
        return None


def main():
    """
    Main function to fetch metadata for all photos in NASA Flickr photosets
    """
    print("NASA Flickr Photos Metadata Retriever")
    print("=" * 50)

    # Check if API key is available
    if not FLICKR_API_KEY:
        print("Error: FLICKR_API_KEY not found in environment variables")
        sys.exit(1)

    # Load photo cache
    if not load_photo_cache():
        print("Warning: Could not load photo cache, continuing without cache")

    # Load photosets list
    photosets_data = load_photosets_list()
    if not photosets_data:
        sys.exit(1)

    photosets = photosets_data.get("photosets", [])
    if not photosets:
        print("No photosets found in the loaded data")
        sys.exit(1)

    print(f"Found {len(photosets)} photosets to process")
    print(f"Photo cache: {len(photo_cache)} photos already processed")

    # Show first few photosets for verification
    print("\nFirst few photosets:")
    for i, photoset in enumerate(photosets[:5], 1):
        photoset_id = photoset.get("id")
        photoset_title = photoset.get("title", {}).get("_content", "Untitled")
        photo_count = photoset.get("photos", 0)
        print(f"  {i}. {photoset_title} (ID: {photoset_id}, {photo_count} photos)")

    # Configuration options
    include_detailed_info = True  # Set to False for faster processing
    include_exif = False  # Set to True if you need EXIF data (slower)

    print(f"\nConfiguration:")
    print(f"  Include detailed info: {include_detailed_info}")
    print(f"  Include EXIF data: {include_exif}")
    print(f"  Output folder: {OUTPUT_FOLDER}")
    print(f"  Cache file: {PHOTO_CACHE_FILE}")

    # Process each photoset
    successful_count = 0
    failed_count = 0
    total_photos_processed = 0

    for i, photoset in enumerate(photosets, 1):
        photoset_id = photoset.get("id")
        photoset_title = photoset.get("title", {}).get("_content", "Untitled")

        print(f"\n[{i}/{len(photosets)}] Processing: {photoset_title}")
        print(f"Photoset ID: {photoset_id}")

        # Check if file already exists and load existing data
        existing_data = load_existing_photoset_data(photoset_id, photoset_title)

        if existing_data:
            # Check if photoset is complete
            metadata = existing_data.get("metadata", {})
            total_photos_in_album = metadata.get("total_photos_in_album", 0)
            photos_processed = metadata.get("photos_processed", 0)
            photos_skipped = metadata.get("photos_skipped", 0)

            if photos_processed + photos_skipped >= total_photos_in_album:
                print(
                    f"  Skipping - photoset already complete: {photos_processed + photos_skipped}/{total_photos_in_album} photos"
                )
                successful_count += 1
                continue
            else:
                print(
                    f"  Resuming partial photoset: {photos_processed + photos_skipped}/{total_photos_in_album} photos already processed"
                )

        try:
            # Process the photoset (will resume from existing data if available)
            result = process_photoset(
                photoset,
                include_detailed_info=include_detailed_info,
                include_exif=include_exif,
                existing_data=existing_data,
            )

            if result:
                # Save the result
                if save_photoset_data(result, photoset_id, photoset_title):
                    successful_count += 1
                    photos_processed_in_this_set = result["metadata"][
                        "photos_processed"
                    ]
                    total_photos_processed += photos_processed_in_this_set
                    print(
                        f"  ✓ Successfully processed photoset: {photoset_title} ({photos_processed_in_this_set} photos)"
                    )
                else:
                    failed_count += 1
                    print(f"  ✗ Failed to save photoset: {photoset_title}")
            else:
                failed_count += 1
                print(f"  ✗ Failed to process photoset: {photoset_title}")

        except KeyboardInterrupt:
            print(f"\nProcess interrupted by user.")
            break
        except Exception as e:
            failed_count += 1
            print(f"  ✗ Error processing photoset {photoset_title}: {e}")

        # Save cache periodically (every 10 photos processed)
        if total_photos_processed >= 10 and total_photos_processed % 10 == 0:
            save_photo_cache()

        # Progress update
        if i % 10 == 0 or i == len(photosets):
            print(f"\nProgress: {i}/{len(photosets)} photosets processed")
            print(f"Successful: {successful_count}, Failed: {failed_count}")
            print(f"Cache: {cache_hits} hits, {cache_misses} misses")
            print(f"Total photos processed: {total_photos_processed}")

    # Save final cache
    save_photo_cache()

    # Final summary
    print(f"\n" + "=" * 50)
    print(f"Processing complete!")
    print(f"Total photosets: {len(photosets)}")
    print(f"Successfully processed: {successful_count}")
    print(f"Failed: {failed_count}")
    print(f"Output folder: {OUTPUT_FOLDER}")
    print(f"Cache statistics: {cache_hits} hits, {cache_misses} misses")
    print(f"Total photos processed (deduplicated): {len(photo_cache)}")


def test_input_format():
    """
    Test function to validate the input format without making API calls
    """
    print("Testing input format...")

    photosets_data = load_photosets_list()
    if not photosets_data:
        return False

    photosets = photosets_data.get("photosets", [])
    if not photosets:
        print("No photosets found")
        return False

    print(f"✓ Found {len(photosets)} photosets")

    # Check first photoset structure
    if photosets:
        first_photoset = photosets[0]
        required_fields = ["id", "title"]

        for field in required_fields:
            if field not in first_photoset:
                print(f"✗ Missing required field: {field}")
                return False

        print(f"✓ Input format validation passed")
        print(f"  Sample photoset ID: {first_photoset.get('id')}")
        print(
            f"  Sample photoset title: {first_photoset.get('title', {}).get('_content', 'N/A')}"
        )

    return True


if __name__ == "__main__":
    # Uncomment the line below to test input format first
    # test_input_format()

    main()
