"""
Script to count Earth photography photos with corner coordinate data.
Reads the JSON manifest files generated by 9_web_earth_photography.py
and counts how many photos have corner data vs total photos.
"""

import os
import json
import argparse
from datetime import datetime
from collections import defaultdict
from dotenv import load_dotenv
from rich.console import Console
from rich.table import Table
from rich.progress import (
    Progress,
    SpinnerColumn,
    TextColumn,
    BarColumn,
    TaskProgressColumn,
)

console = Console()

# Load environment variables from .env file
load_dotenv(dotenv_path="../../../.env")

# Constants
IMAGES_FOLDER = os.getenv("WEB_ASSETS_FOLDER") + "photos_earth/"
START_DATE = "2000-11-01"
END_DATE = datetime.now().strftime("%Y-%m-%d")


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Count Earth photography photos with corner coordinate data."
    )
    parser.add_argument(
        "--start-date",
        type=str,
        default=START_DATE,
        help=f"Start date in YYYY-MM-DD format. Defaults to {START_DATE}",
    )
    parser.add_argument(
        "--end-date",
        type=str,
        default=END_DATE,
        help=f"End date in YYYY-MM-DD format. Defaults to today ({END_DATE})",
    )
    parser.add_argument(
        "--by-year",
        action="store_true",
        help="Show breakdown by year",
    )
    parser.add_argument(
        "--by-month",
        action="store_true",
        help="Show breakdown by month",
    )
    return parser.parse_args()


def count_manifest_file(manifest_path):
    """
    Count photos with and without corner data in a manifest file.
    Returns (total_photos, photos_with_corners, photos_with_center_only, corner_points_count)
    """
    try:
        with open(manifest_path, "r") as f:
            data = json.load(f)

        if not isinstance(data, list):
            return 0, 0, 0, 0

        total = len(data)
        with_corners = sum(1 for entry in data if "corners" in entry)
        with_center_only = sum(
            1 for entry in data if "lat" in entry and "corners" not in entry
        )

        # Count total corner points
        corner_points = 0
        for entry in data:
            if "corners" in entry and isinstance(entry["corners"], dict):
                # Corners is an object with ul, ur, ll, lr keys
                corner_points += len(entry["corners"])

        return total, with_corners, with_center_only, corner_points
    except (IOError, json.JSONDecodeError) as e:
        return 0, 0, 0, 0


def main():
    args = parse_arguments()

    try:
        start_date = datetime.strptime(args.start_date, "%Y-%m-%d")
        end_date = datetime.strptime(args.end_date, "%Y-%m-%d")
    except ValueError as e:
        console.print(
            f"[bold red]Error: Invalid date format. Use YYYY-MM-DD.[/bold red]"
        )
        return

    console.print(
        f"[bold cyan]Counting Earth photography corner data from {args.start_date} to {args.end_date}[/bold cyan]\n"
    )

    # Statistics
    total_photos = 0
    total_with_corners = 0
    total_with_center_only = 0
    total_manifests = 0
    total_corner_points = 0

    # Breakdown tracking
    by_year = defaultdict(
        lambda: {"total": 0, "corners": 0, "center_only": 0, "corner_points": 0}
    )
    by_month = defaultdict(
        lambda: {"total": 0, "corners": 0, "center_only": 0, "corner_points": 0}
    )

    # Find all manifest files
    manifest_files = []

    for year in range(start_date.year, end_date.year + 1):
        year_folder = os.path.join(IMAGES_FOLDER, str(year))
        if not os.path.exists(year_folder):
            continue

        for month in range(1, 13):
            month_folder = os.path.join(year_folder, f"{month:02d}")
            if not os.path.exists(month_folder):
                continue

            for day in range(1, 32):
                date_str = f"{year}-{month:02d}-{day:02d}"
                try:
                    check_date = datetime.strptime(date_str, "%Y-%m-%d")
                    if check_date < start_date or check_date > end_date:
                        continue
                except ValueError:
                    continue

                manifest_file = os.path.join(
                    month_folder, f"images-manifest_{year}-{month:02d}-{day:02d}.json"
                )
                if os.path.exists(manifest_file):
                    manifest_files.append((manifest_file, year, month))

    if not manifest_files:
        console.print(
            "[yellow]No manifest files found in the specified date range.[/yellow]"
        )
        return

    # Process all manifests with progress bar
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        console=console,
    ) as progress:
        task = progress.add_task(
            f"[cyan]Processing {len(manifest_files)} manifest files...",
            total=len(manifest_files),
        )

        for manifest_path, year, month in manifest_files:
            total, corners, center_only, corner_points = count_manifest_file(
                manifest_path
            )

            total_photos += total
            total_with_corners += corners
            total_with_center_only += center_only
            total_corner_points += corner_points
            total_manifests += 1

            # Track by year
            by_year[year]["total"] += total
            by_year[year]["corners"] += corners
            by_year[year]["center_only"] += center_only
            by_year[year]["corner_points"] += corner_points

            # Track by month
            month_key = f"{year}-{month:02d}"
            by_month[month_key]["total"] += total
            by_month[month_key]["corners"] += corners
            by_month[month_key]["center_only"] += center_only
            by_month[month_key]["corner_points"] += corner_points

            progress.update(task, advance=1)

    console.print()

    # Summary table
    summary_table = Table(
        title="[bold]Earth Photography Corner Data Summary[/bold]",
        show_header=True,
        header_style="bold magenta",
    )
    summary_table.add_column("Metric", style="cyan", width=35)
    summary_table.add_column("Count", justify="right", style="green")
    summary_table.add_column("Percentage", justify="right", style="yellow")

    summary_table.add_row("Total Manifest Files", f"{total_manifests:,}", "")
    summary_table.add_row("Total Photos", f"{total_photos:,}", "100%")
    summary_table.add_row(
        "Photos WITH Corner Data",
        f"{total_with_corners:,}",
        (
            f"{(total_with_corners / total_photos * 100):.1f}%"
            if total_photos > 0
            else "N/A"
        ),
    )
    summary_table.add_row(
        "Total Corner Points",
        f"{total_corner_points:,}",
        (
            f"Avg: {(total_corner_points / total_with_corners):.1f}"
            if total_with_corners > 0
            else "N/A"
        ),
    )
    summary_table.add_row(
        "Photos with Center Only (no corners)",
        f"{total_with_center_only:,}",
        (
            f"{(total_with_center_only / total_photos * 100):.1f}%"
            if total_photos > 0
            else "N/A"
        ),
    )
    no_location = total_photos - total_with_corners - total_with_center_only
    summary_table.add_row(
        "Photos with NO Location Data",
        f"{no_location:,}",
        f"{(no_location / total_photos * 100):.1f}%" if total_photos > 0 else "N/A",
    )

    console.print(summary_table)

    # By year breakdown
    if args.by_year and by_year:
        console.print()
        year_table = Table(
            title="[bold]Breakdown by Year[/bold]",
            show_header=True,
            header_style="bold magenta",
        )
        year_table.add_column("Year", style="cyan")
        year_table.add_column("Total", justify="right", style="white")
        year_table.add_column("With Corners", justify="right", style="green")
        year_table.add_column("Corner %", justify="right", style="yellow")
        year_table.add_column("Corner Points", justify="right", style="blue")
        year_table.add_column("Center Only", justify="right", style="blue")
        year_table.add_column("No Location", justify="right", style="red")

        for year in sorted(by_year.keys()):
            data = by_year[year]
            no_loc = data["total"] - data["corners"] - data["center_only"]
            pct = (
                f"{(data['corners'] / data['total'] * 100):.1f}%"
                if data["total"] > 0
                else "N/A"
            )
            year_table.add_row(
                str(year),
                f"{data['total']:,}",
                f"{data['corners']:,}",
                pct,
                f"{data['corner_points']:,}",
                f"{data['center_only']:,}",
                f"{no_loc:,}",
            )

        console.print(year_table)

    # By month breakdown
    if args.by_month and by_month:
        console.print()
        month_table = Table(
            title="[bold]Breakdown by Month[/bold]",
            show_header=True,
            header_style="bold magenta",
        )
        month_table.add_column("Month", style="cyan")
        month_table.add_column("Total", justify="right", style="white")
        month_table.add_column("With Corners", justify="right", style="green")
        month_table.add_column("Corner %", justify="right", style="yellow")
        month_table.add_column("Corner Points", justify="right", style="blue")
        month_table.add_column("Center Only", justify="right", style="blue")
        month_table.add_column("No Location", justify="right", style="red")

        for month_key in sorted(by_month.keys()):
            data = by_month[month_key]
            no_loc = data["total"] - data["corners"] - data["center_only"]
            pct = (
                f"{(data['corners'] / data['total'] * 100):.1f}%"
                if data["total"] > 0
                else "N/A"
            )
            month_table.add_row(
                month_key,
                f"{data['total']:,}",
                f"{data['corners']:,}",
                pct,
                f"{data['corner_points']:,}",
                f"{data['center_only']:,}",
                f"{no_loc:,}",
            )

        console.print(month_table)

    console.print(f"\n[bold green]✓ Analysis complete![/bold green]")


if __name__ == "__main__":
    main()
