version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ${DOCKER_SSL_CERTS_DIR}:/etc/pki/tls/certs
      - ${DOCKER_SSL_PRIVATE_DIR}:/etc/pki/tls/private
    ports:
      - "443:443"
    environment:
      - VITE_BASE_STATIC_URL=${VITE_BASE_STATIC_URL}
    networks:
      - boilerplate-network

networks:
  boilerplate-network:
    driver: bridge
