name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Rebuild native modules
        run: npm rebuild

      - name: List installed dependencies
        run: npm ls --depth=0

      - name: Build the app
        run: npm run build

      - name: Deploy to DreamHost
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
        run: |
          if [ -d .local/vite/dist ]; then
            rsync -avz --delete .local/vite/dist/ ${{ secrets.DREAMHOST_USER }}@${{ secrets.DREAMHOST_HOST }}:${{ secrets.DREAMHOST_PATH_DEV }}
          else
            echo "Error: .local/vite/dist directory is missing. Skipping deployment."
            exit 1
          fi
