name: Deploy React App

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Rebuild native modules
        run: npm rebuild

      # - name: List installed dependencies
      #   run: npm ls --depth=0

      - name: Create .env file
        run: |
          echo "VITE_BASE_STATIC_URL=${{ secrets.VITE_BASE_STATIC_URL }}" >> .env
          echo "VITE_IMAGE_BASE_URL=${{ secrets.VITE_IMAGE_BASE_URL }}" >> .env
          echo "VITE_CESIUM_ION_TOKEN=${{ secrets.VITE_CESIUM_ION_TOKEN }}" >> .env

      - name: Build the app
        run: npm run build

      - name: Deploy to DreamHost
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
          DREAMHOST_PRIVATE_KEY: "${{ secrets.DREAMHOST_PRIVATE_KEY }}"
          DREAMHOST_HOST: "${{ secrets.DREAMHOST_HOST }}"
          DREAMHOST_USER: "${{ secrets.DREAMHOST_USER }}"
          DREAMHOST_PATH: "${{ secrets.DREAMHOST_PATH }}"
          DREAMHOST_PATH_DEV: "${{ secrets.DREAMHOST_PATH_DEV }}"
        run: |
          mkdir -p ~/.ssh
          echo "$DREAMHOST_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H "$DREAMHOST_HOST" >> ~/.ssh/known_hosts

          if [ "${GITHUB_REF}" == "refs/heads/prod" ]; then
            DEPLOY_PATH="$DREAMHOST_PATH"
          elif [ "${GITHUB_REF}" == "refs/heads/dev" ]; then
            DEPLOY_PATH="$DREAMHOST_PATH_DEV"
          else
            echo "Unknown branch. Skipping deployment."
            exit 1
          fi

          ssh "$DREAMHOST_USER@$DREAMHOST_HOST" "mkdir -p $DEPLOY_PATH"
          if [ -d .local/vite/dist ]; then
            rsync -avz --delete .local/vite/dist/ "$DREAMHOST_USER@$DREAMHOST_HOST":"$DEPLOY_PATH"
          else
            echo "Error: .local/vite/dist directory is missing. Skipping deployment."
            exit 1
          fi
